import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import prismadb from "lib/prismadb";
export const metadata = {
  title: "Bio Meal",
  description: "Generated by create next app",
  icon: "/icon.svg",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" overflow-x-hidden bg-white flex flex-col items-center justify-between min-h-screen">
        <Header />
        <div className=" max-w-[1280px] w-full h-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
