import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Bio Meal",
  description: "Generated by create next app",
  icon: "/icon.svg",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <Header />
        {children}
      </body>
    </html>
  );
}
